version: '3'

networks:
  postgres_test:
    driver: bridge

services:
  integration_tests:
    build:
      context: ../
      dockerfile: ./deployment/test.Dockerfile
    environment:
      TESTS_POSTGRES_DSN: 'host=postgres_test port=5432 user=postgres password=test dbname=postgres_test sslmode=disable'
      WAIT_HOSTS: postgres_test:5432
    networks:
      - postgres_test

  postgres_test:
    image: postgres:latest
    hostname: postgres_test
    container_name: postgres_test
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=postgres_test
    volumes:
      - ../migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres_test
