version: "3"

networks:
  postgres:
    driver: bridge

services:
  rotator:
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
      args:
        - CONFIG_FILE_NAME=config
    container_name: rotator
    environment:
      WAIT_HOSTS: postgres:5432
    restart: on-failure
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - 8080
      - 8081
    depends_on:
      - postgres
    networks:
      - postgres

  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=rotator
    volumes:
      - ../migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres
