logger:
  level: info
api:
  host: 127.0.0.1
  port: 8080
storage:
  type: sql
  connectionString: host=localhost port=5432 user=postgres password=qwerty dbname=rotator sslmode=disable
rmq:
  uri: amqp://guest:guest@localhost:5672/
  name: events
